name: "List PR files"
description: "List pull request files"
inputs:
  token:
    description: Access token used to authenticate with the GitHub API.
    default: ${{ github.token }}
    required: true
outputs:
  files:
    description: "The stringified array containing the name of all files in the pull request"
runs:
  using: "node12"
  main: "dist/index.js"
